# Default values for hello-ring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploy: true
replicaCount: 1

image:
  repository: myRepo
  tag: myTag
  pullPolicy: IfNotPresent

application:
  ports:
    - containerPort: 8080
  selector:
    app.kubernetes.io/name: "hello-rings-featurea"
ring:
  name: featurea
  claim: featurea
  matchRequest: PathPrefix(`/`) && Headers(`x-ring`, `featurea`)
