trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'hellorings_acr'
    repository: 'hellorings'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.SourceBranchName)-$(Build.BuildId)'
