trigger:
  branches:
    include:
    - master
    - '*'
  paths:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'ydawgie_hellorings_acr'
    repository: 'gc_hellorings_test'
    command: 'buildAndPush'
    Dockerfile: '**/src/Dockerfile'
    tags: 'hello-rings-$(Build.SourceBranchName)-$(Build.BuildId)'
