trigger:
  branches:
    include:
    - 'ydawgie'

jobs:
- job: RingRemoval
  displayName: ring_removal
  timeoutInMinutes: 90
  pool:
    vmImage: 'Ubuntu-16.04'
    timeoutInMinutes: 90
  steps:
  - script: |
      repo_url=$SRC_REPO
      repo_url="${repo_url#http://}"
      repo_url="${repo_url#https://}"
      git push "https://$ACCESS_TOKEN_SECRET@$repo_url" --delete $(Build.SourceBranchName)
    displayName: 'Delete Git Branch'
  - script: |
      # download build.sh from microsoft/bedrock
      curl https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/build.sh > build.sh
      chmod +x ./build.sh

      # install hub if using GitHub repos
      sudo add-apt-repository ppa:cpick/hub
      sudo apt-get update
      sudo apt-get install hub

      # source build.sh
      . build.sh --source-only

      # execute build.sh functions
      verify_access_token
      init
      helm init
      get_os
      get_fab_version
      download_fab
      git_connect

      # extract branch name and build # from the full subcomponent
      branch_name=$(Build.SourceBranchName)
      build_number=$(Build.BuildNumber)

      # run 'fab remove' to remove ring
      echo "FAB REMOVE"
      fab remove hello-rings-$branch_name

      echo "GIT ADD"
      git add -A

      pr_branch_name="PR-ring-removal-$branch_name-$build_number"
      git checkout -b $pr_branch_name

      # set git identity
      git config user.email "admin@azuredevops.com"
      git config user.name "Automated Account"

      echo "GIT COMMIT"
      git commit -m "Deleting ring $branch_name"

      echo "GIT PUSH"
      git_push origin $pr_branch_name

      # create pull request using hub
      export GITHUB_TOKEN=$ACCESS_TOKEN_SECRET
      hub version
      hub pull-request -m "Removing RING $branch_name"
    displayName: 'Remove Subcomponent'
