apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}-{{ .Values.majorVersion }}-{{ .Values.ringName }}
  labels:
    name: {{ .Values.serviceName }}
    version: {{ .Values.majorVersion }}
    ring: {{ .Values.ringName }}
spec:
  replicas: {{ .Values.application.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.serviceName }}
      version: {{ .Values.majorVersion }}
      ring: {{ .Values.ringName }}
  template:
    metadata:
      labels:
        name: {{ .Values.serviceName }}
        version: {{ .Values.majorVersion }}
        ring: {{ .Values.ringName }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{ toYaml .Values.application.ports }}
