# Source: hello-ring/templates/ring.yaml
apiVersion: rings.microsoft.com/v1alpha1
kind: Ring
metadata:
  name: {{ .Values.ring.name }}
spec:
  # Deploy to environment
  deploy: {{ .Values.deploy }}
  # Custom Claims
  claim: {{ .Values.ring.claim }}
  entryPoints:
    # Source of traffic (eg: 80 or 443)
    - http
    - https
    - internal
  match: {{ .Values.ring.matchRequest }}
  selector:
    {{ toYaml .Values.application.selector }}
