apiVersion: rings.microsoft.com/v1alpha1
kind: Ring
metadata:
  name: featurea
spec:
  # Deploy to environment
  deploy: true
  # Custom Claims
  claim: featurea
  entryPoints:
    # Source of traffic (eg: 80 or 443)
    - http
    - https
    - internal
  match: PathPrefix(`/query/v1`) && Headers(`x-ring`, `featurea`)
  selector:
    app.kubernetes.io/name: hello-rings-featurea
