# Source: hello-ring/templates/ring.yaml
apiVersion: rings.microsoft.com/v1alpha1
kind: Ring
metadata:
  name: featurec
spec:
  # Deploy to environment
  deploy: true
  # Custom Claims
  claim: featurec
  entryPoints:
    # Source of traffic (eg: 80 or 443)
    - http
    - https
    - internal
  match: PPathPrefix(`/`) && Headers(`x-ring`, `featurec`)
  selector:
    app.kubernetes.io/name: {{ include "hello-ring.name" . }}
