# Source: hello-ring/templates/ring.yaml
apiVersion: rings.microsoft.com/v1alpha1
kind: Ring
metadata:
  name: master
spec:
  # Deploy to environment
  deploy: true
  # Custom Claims
  claim: production
  entryPoints:
    # Source of traffic (eg: 80 or 443)
    - http
    - https
    - internal
  match: PathPrefix(`/query/v1`) && Headers(`x-ring`, `production`)
  selector:
    app.kubernetes.io/name: hello-rings-master
