apiVersion: v1
kind: Pod
metadata:
  name: prod-ring-crd
  labels:
    ring: prod
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
